#ifndef DMS_S3_CONFIG_H
#define DMS_S3_CONFIG_H

#if defined(__has_include)
#if __has_include("dms_secrets.h")
#include "dms_secrets.h"
#endif
#endif

#ifndef DMS_WIFI_SSID
#define DMS_WIFI_SSID ""
#endif
#ifndef DMS_WIFI_PASSWORD
#define DMS_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#endif
#ifndef DMS_MQTT_BROKER_URL
#define DMS_MQTT_BROKER_URL "mqtt://YOUR_MQTT_BROKER"
#endif

#define DMS_S3_DEVICE_ID "esp32s3_dms_01"
#define DMS_PC_DEVICE_ID "pc_dms_001"

/* USER ACTION REQUIRED: validate these pins on the real S3 board. */
#define I2S_BCLK_PIN 14
#define I2S_LRC_PIN 4
#define I2S_DIN_PIN 5
#define I2S_SD_PIN 6
#define IR_LED_PIN 7
#define STATUS_LED_PIN 48

#define DMS_OBSERVATION_TIMEOUT_MS 1500U
#define DMS_MQTT_RECONNECT_TIMEOUT_MS 5000U
#define DMS_MAX_PROCESSING_TIME_MS 10000.0f
#define DMS_EAR_CLOSED_START 0.18f
#define DMS_EAR_CLOSED_RECOVER 0.22f
#define DMS_MAR_YAWN_START 0.60f
#define DMS_MAR_YAWN_RECOVER 0.50f

#define BLINK_MICRO_SLEEP_MS 500U
#define BLINK_DEEP_SLEEP_MS 1500U
#define YAWN_DURATION_MS 2500U
#define YAWN_RECOVERY_MS 1000U
#define PERCLOS_WINDOW_MS 60000U
#define PERCLOS_MIN_VALID_OBSERVATION_MS 10000U
#define PERCLOS_ALERT_RATIO 0.40f
#define PERCLOS_MAX_OBSERVATION_GAP_MS 1000U
#define DMS_PERCLOS_MAX_INTERVALS 128U
#define ALERT_COOLDOWN_MS 10000U

#define DMS_MQTT_KEEPALIVE_SECONDS 30U
#define DMS_AUDIO_QUEUE_LENGTH 4U

#endif /* DMS_S3_CONFIG_H */
